name: Tonton Auto Scraper

on:
  schedule:
    - cron: '*/15 * * * *' # Jalankan setiap 15 minit automatik
  workflow_dispatch: # Boleh tekan manual dari GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Tonton Browser Session
        uses: actions/cache@v4
        with:
          path: ./tonton_session
          key: ${{ runner.os }}-tonton-session
          restore-keys: |
            ${{ runner.os }}-tonton-session

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests playwright
          playwright install chromium

      - name: Run script
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          NAMESPACE_ID: ${{ secrets.NAMESPACE_ID }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          python tonton.py
